name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/pnpm:v1.2.0
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pnpm i
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm t
